# drop unknown EDA

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from imblearn.over_sampling import SMOTE

df = pd.read_csv("./bank-additional/bank-additional/bank-additional-full.csv",delimiter=";")
df

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

#### drop yg aneh2

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [122]:
# df.drop(['nr.employed','euribor3m','cons.conf.idx','cons.price.idx','emp.var.rate'],axis=1,inplace=True)
df.drop(['emp.var.rate','contact','housing','loan','previous','marital'],axis=1,inplace=True)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   education       41188 non-null  object
 3   default         41188 non-null  object
 4   month           41188 non-null  object
 5   day_of_week     41188 non-null  object
 6   duration        41188 non-null  int64
 7   campaign        41188 non-null  int64
 8   pdays           41188 non-null  int64
 9   poutcome        41188 non-null  object
 10  cons.price.idx  41188 non-null  float64
 11  cons.conf.idx   41188 non-null  float64
 12  euribor3m       41188 non-null  float64
 13  nr.employed     41188 non-null  float64
 14  y               41188 non-null  object
dtypes: float64(4), int64(4), object(7)
memory usage: 4.7+ MB

#### genapin duration

In [124]:
df['duration'] = (df['duration']/60).round()

#### drop column

In [125]:
df.drop(['day_of_week','default','pdays'],axis=1,inplace=True)
df.head()

,age,job,education,month,duration,campaign,poutcome,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,basic.4y,may,4.0,1,nonexistent,93.994,-36.4,4.857,5191.0,no
1,57,services,high.school,may,2.0,1,nonexistent,93.994,-36.4,4.857,5191.0,no
2,37,services,high.school,may,4.0,1,nonexistent,93.994,-36.4,4.857,5191.0,no
3,40,admin.,basic.6y,may,3.0,1,nonexistent,93.994,-36.4,4.857,5191.0,no
4,56,services,high.school,may,5.0,1,nonexistent,93.994,-36.4,4.857,5191.0,no

#### drop unknown

In [126]:

Q1_duration = df['duration'].quantile(0.25)
Q3_duration = df['duration'].quantile(0.75)
IQR_duration = Q3_duration - Q1_duration

lower_bound_duration = Q1_duration - 1.5 * IQR_duration
upper_bound_duration = Q3_duration + 1.5 * IQR_duration

df = df[(df['duration'] >= max(0, lower_bound_duration)) & 
        (df['duration'] <= upper_bound_duration)]

Q1_campaign = df['campaign'].quantile(0.25)
Q3_campaign = df['campaign'].quantile(0.75)
IQR_campaign = Q3_campaign - Q1_campaign

lower_bound_campaign = Q1_campaign - 1.5 * IQR_campaign
upper_bound_campaign = Q3_campaign + 1.5 * IQR_campaign

df = df[(df['campaign'] >= max(1, lower_bound_campaign)) & 
        (df['campaign'] <= upper_bound_campaign)]

print(f"New Upper Bound for 'duration' (1.5*IQR): {upper_bound_duration:.2f}")
print(f"New Upper Bound for 'campaign' (1.5*IQR): {upper_bound_campaign:.2f}")
print(f"DataFrame shape after outlier removal: {df.shape}")

New Upper Bound for 'duration' (1.5*IQR): 9.50
New Upper Bound for 'campaign' (1.5*IQR): 6.00
DataFrame shape after outlier removal: (35102, 12)

In [127]:
df = df[df['education'] != 'unknown']

In [128]:
# df = df[df['housing'] != 'unknown']

In [129]:
df = df[df['job'] != 'unknown']

In [130]:
# df = df[df['marital'] != 'unknown']

#### feature age = bining & ordinal

In [131]:
'''
min_age = df['age'].min()   # 17
max_age = df['age'].max()   # 98

# 5‑year buckets: [17–21], [22–26], … , [87–91] (last bucket includes all >90)
bin_edges = list(range(min_age, max_age + 1, 5))      # e.g. [17, 22, 27, ..., 93]
# add an upper bound that is bigger than any age so the last value falls in
bin_edges.append(float('inf'))

# Labels for readability (optional)
labels = [f'{l}-{r-1}' for l, r in zip(bin_edges[:-2], bin_edges[1:-1])]
labels.append(f'{bin_edges[-2]}+')

# ── Apply cut ───────────────────────────────────────────
df['age_bin'] = pd.cut(df['age'],
                       bins=bin_edges,
                       labels=labels,
                       right=False,          # left‑inclusive [l,r)
                       include_lowest=True)  # include the very first value

# ── Ordinal encoding (1 = first bin, 2 = second …) ───────
df['age_ordinal'] = df['age_bin'].cat.codes + 1   # .codes gives 0‑based int

df.head()
'''

"\nmin_age = df['age'].min()   # 17\nmax_age = df['age'].max()   # 98\n\n# 5‑year buckets: [17–21], [22–26], … , [87–91] (last bucket includes all >90)\nbin_edges = list(range(min_age, max_age + 1, 5))      # e.g. [17, 22, 27, ..., 93]\n# add an upper bound that is bigger than any age so the last value falls in\nbin_edges.append(float('inf'))\n\n# Labels for readability (optional)\nlabels = [f'{l}-{r-1}' for l, r in zip(bin_edges[:-2], bin_edges[1:-1])]\nlabels.append(f'{bin_edges[-2]}+')\n\n# ── Apply cut ───────────────────────────────────────────\ndf['age_bin'] = pd.cut(df['age'],\n                       bins=bin_edges,\n                       labels=labels,\n                       right=False,          # left‑inclusive [l,r)\n                       include_lowest=True)  # include the very first value\n\n# ── Ordinal encoding (1\u202f=\u202ffirst bin, 2\u202f=\u202fsecond …) ───────\ndf['age_ordinal'] = df['age_bin'].cat.codes + 1   # .codes gives 0‑based int\n\ndf.head()\n"

In [132]:
# drop obsolete age feature :
# df.drop(['age','age_bin'],axis = 1,inplace=True)

In [133]:
# Convert y from yes/no to 0/1
df['y'] = df['y'].map({'yes': 1, 'no': 0})

#### contact binary encoder

In [134]:
from category_encoders import BinaryEncoder,OneHotEncoder,TargetEncoder


#encoder = BinaryEncoder(cols=['contact'])
#df = encoder.fit_transform(df)

#### education OHE

In [135]:
ohe = TargetEncoder(cols=['education'])
df = ohe.fit_transform(df,df['y'])

df.head()

,age,job,education,month,duration,campaign,poutcome,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,0.077253,may,4.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0
1,57,services,0.072340,may,2.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0
2,37,services,0.072340,may,4.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0
3,40,admin.,0.038981,may,3.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0
4,56,services,0.072340,may,5.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0

#### housing binary

In [136]:
#encoder2 = BinaryEncoder(cols=['housing'])
#df = encoder2.fit_transform(df)

df.head()

,age,job,education,month,duration,campaign,poutcome,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,0.077253,may,4.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0
1,57,services,0.072340,may,2.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0
2,37,services,0.072340,may,4.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0
3,40,admin.,0.038981,may,3.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0
4,56,services,0.072340,may,5.0,1,nonexistent,93.994,-36.4,4.857,5191.0,0

#### job OHE,loan OHE, marital OHE,month OHE, poutcome OHE

contact,previous,housing,loan

In [137]:
encoder3 = TargetEncoder(cols=['job'])
df = encoder3.fit_transform(df,df['y'])

#encoder4 = BinaryEncoder(cols=['loan'])
#df = encoder4.fit_transform(df)

'''
encoder5 = TargetEncoder(cols=['marital'])
df = encoder5.fit_transform(df,df['y'])
'''
encoder6 = TargetEncoder(cols=['month'])
df = encoder6.fit_transform(df,df['y'])

encoder7 = TargetEncoder(cols=['poutcome'])
df = encoder7.fit_transform(df,df['y'])

df.head()

,age,job,education,month,duration,campaign,poutcome,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,0.080738,0.077253,0.028692,4.0,1,0.053361,93.994,-36.4,4.857,5191.0,0
1,57,0.044547,0.072340,0.028692,2.0,1,0.053361,93.994,-36.4,4.857,5191.0,0
2,37,0.044547,0.072340,0.028692,4.0,1,0.053361,93.994,-36.4,4.857,5191.0,0
3,40,0.098575,0.038981,0.028692,3.0,1,0.053361,93.994,-36.4,4.857,5191.0,0
4,56,0.044547,0.072340,0.028692,5.0,1,0.053361,93.994,-36.4,4.857,5191.0,0

In [138]:
df.describe()

,age,job,education,month,duration,campaign,poutcome,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
count,33473.000000,33473.000000,33473.000000,33473.000000,33473.000000,33473.000000,33473.000000,33473.000000,33473.000000,33473.000000,33473.000000,33473.000000
mean,39.861321,0.078332,0.078298,0.078332,3.278971,2.041138,0.078332,93.556683,-40.505261,3.580707,5165.516826,0.078332
std,10.307547,0.049278,0.024213,0.093230,2.132830,1.284355,0.103611,0.580196,4.679815,1.741671,72.241570,0.268697
min,17.000000,0.030808,0.038981,0.028692,0.000000,1.000000,0.053361,92.201000,-50.800000,0.634000,4963.600000,0.000000
25%,32.000000,0.044547,0.072340,0.028692,2.000000,1.000000,0.053361,93.075000,-42.700000,1.334000,5099.100000,0.000000
50%,38.000000,0.074745,0.077253,0.043542,3.000000,2.000000,0.053361,93.444000,-41.800000,4.857000,5191.000000,0.000000
75%,47.000000,0.098575,0.107091,0.073161,4.000000,3.000000,0.053361,93.994000,-36.400000,4.961000,5228.100000,0.000000
max,98.000000,0.277504,0.124266,0.507495,9.000000,6.000000,0.629829,94.767000,-26.900000,5.045000,5228.100000,1.000000

#### train test SPLIT

In [139]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from imblearn.over_sampling import ADASYN,SMOTE

X = df.drop('y', axis=1)  
y = df['y']   

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.30,
    random_state=42,
    stratify=y            
)

X_trainNB, X_testNB, y_trainNB, y_testNB = X_train, X_test, y_train, y_test
ismote = ADASYN(random_state=42,
                sampling_strategy = "auto", 
                n_neighbors = 18)   

X_train_res, y_train_res  = ismote.fit_resample(X_train, y_train)

X_train_res_nb, y_train_res_nb =X_train_res, y_train_res

from collections import Counter
print(Counter(y_train_res))

Counter({1: 21991, 0: 21596})

# **DECISION TREE CLASSIFIER**

#### train-test

In [140]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

clf = DecisionTreeClassifier(random_state=42)   # reproducible tree structure
clf.fit(X_train_res, y_train_res)


y_pred = clf.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}\n")
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

import pandas as pd 

feature_importances = pd.Series(clf.feature_importances_, index=X.columns)
feature_importances = feature_importances.sort_values(ascending=False)

print("\nFeature Importances:")
print(feature_importances)

Accuracy: 0.9162

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.95      0.95      9255
           1       0.47      0.52      0.50       787

    accuracy                           0.92     10042
   macro avg       0.71      0.74      0.72     10042
weighted avg       0.92      0.92      0.92     10042


Confusion Matrix:
[[8787  468]
 [ 374  413]]

Feature Importances:
nr.employed       0.316056
duration          0.276348
month             0.167404
euribor3m         0.055995
age               0.046394
job               0.039028
poutcome          0.032000
education         0.027813
cons.price.idx    0.018348
campaign          0.015947
cons.conf.idx     0.004667
dtype: float64

contact,previous,housing,loan

In [141]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import nevergrad as ng

def evaluate_decision_tree(criterion, max_depth, min_samples_split, min_samples_leaf):
    """
    Evaluates a Decision Tree model using cross-validation.
    Nevergrad minimizes this function, so we return the negative mean score.
    """

    if max_depth == -1:
        max_depth = None

    clf = DecisionTreeClassifier(
        criterion=criterion,
        max_depth=max_depth,
        min_samples_split=min_samples_split,
        min_samples_leaf=min_samples_leaf,
        random_state=42
    )

    scores = cross_val_score(clf, X_train, y_train, cv=5, scoring='accuracy')
    return -np.mean(scores)

param_space = ng.p.Instrumentation(
    criterion=ng.p.Choice(['gini', 'entropy', 'log_loss']),
    max_depth=ng.p.Choice([-1] + list(range(1, 21))),
    min_samples_split=ng.p.Scalar(lower=2, upper=10).set_integer_casting(),
    min_samples_leaf=ng.p.Scalar(lower=1, upper=5).set_integer_casting(),
)

optimizer = ng.optimizers.OnePlusOne(parametrization=param_space, budget=50)
best_suggestion = optimizer.minimize(
    lambda *args, **kwargs: evaluate_decision_tree(*args, **kwargs)
)

best_kwargs = best_suggestion.kwargs
best_params = {
    'criterion': best_kwargs['criterion'],
    'max_depth': None if best_kwargs['max_depth'] == -1 else int(best_kwargs['max_depth']),
    'min_samples_split': int(best_kwargs['min_samples_split']),
    'min_samples_leaf': int(best_kwargs['min_samples_leaf'])
}

print("\n--- Optimization Results ---")
print("Best Hyperparameters Found:")
print(best_params)

clf_best = DecisionTreeClassifier(**best_params, random_state=0)
clf_best.fit(X_train, y_train)
y_pred = clf_best.predict(X_test)

print("\n--- Final Model Performance on Test Set ---")
print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

feature_importances = pd.Series(clf_best.feature_importances_, index=X.columns)
feature_importances = feature_importances.sort_values(ascending=False)

print("\nFeature Importances:")
print(feature_importances)

--- Optimization Results ---
Best Hyperparameters Found:
{'criterion': 'entropy', 'max_depth': 7, 'min_samples_split': 4, 'min_samples_leaf': 4}

--- Final Model Performance on Test Set ---
Accuracy: 0.9404

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      9255
           1       0.65      0.52      0.58       787

    accuracy                           0.94     10042
   macro avg       0.80      0.75      0.77     10042
weighted avg       0.94      0.94      0.94     10042


Confusion Matrix:
[[9032  223]
 [ 376  411]]

Feature Importances:
nr.employed       0.478268
duration          0.235147
month             0.112847
euribor3m         0.073910
poutcome          0.033376
age               0.019535
cons.price.idx    0.016697
job               0.013063
education         0.007304
cons.conf.idx     0.006082
campaign          0.003771
dtype: float64

# **NAIVE BAYES**

In [142]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Initialize the Gaussian Naive Bayes classifier
# Note: No 'random_state' is needed as Naive Bayes is a deterministic algorithm.
nb_clf_ = GaussianNB()

# Fit the classifier to the training data (assuming X_train_res and y_train_res are defined)
nb_clf_.fit(X_train_res_nb, y_train_res_nb)

# Make predictions on the test set
y_predNB = nb_clf_.predict(X_testNB)

# --- Model Evaluation ---
print("--- Gaussian Naive Bayes Model Performance ---")
print(f"Accuracy: {accuracy_score(y_testNB, y_pred):.4f}\n")
print("Classification Report:")
print(classification_report(y_testNB, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_testNB, y_pred))

# --- Feature Importance Note ---
# The following section is REMOVED/COMMENTED OUT because 
# GaussianNB (a Naive Bayes model) does not have a feature_importances_ attribute.
# 
# import pandas as pd 
# feature_importances = pd.Series(nb_clf.feature_importances_, index=X.columns)
# feature_importances = feature_importances.sort_values(ascending=False)
# print("\nFeature Importances:")
# print(feature_importances)

--- Gaussian Naive Bayes Model Performance ---
Accuracy: 0.9404

Classification Report:
              precision    recall  f1-score   support

           0       0.96      0.98      0.97      9255
           1       0.65      0.52      0.58       787

    accuracy                           0.94     10042
   macro avg       0.80      0.75      0.77     10042
weighted avg       0.94      0.94      0.94     10042


Confusion Matrix:
[[9032  223]
 [ 376  411]]

In [143]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import nevergrad as ng

def evaluate_nb(log10_var_smoothing):
    """
    Evaluates GaussianNB via cross-validation.
    Nevergrad minimizes this function => return negative mean accuracy.
    We optimize log10(var_smoothing) to search on a log scale.
    """
    var_smoothing = 10.0 ** log10_var_smoothing
    clf_ = GaussianNB(var_smoothing=var_smoothing)
    scores = cross_val_score(clf_, X_trainNB, y_trainNB, cv=5, scoring='accuracy')
    return -np.mean(scores)

param_space = ng.p.Instrumentation(
    log10_var_smoothing=ng.p.Scalar(lower=-12, upper=-6)
)

optimizer = ng.optimizers.OnePlusOne(parametrization=param_space, budget=50)
best_suggestion = optimizer.minimize(lambda *a, **k: evaluate_nb(*a, **k))
best_log10_vs = float(best_suggestion.kwargs['log10_var_smoothing'])
best_var_smoothing = 10.0 ** best_log10_vs

print("\n--- Optimization Results (Naive Bayes) ---")
print({"var_smoothing": best_var_smoothing})

nb_best_ = GaussianNB(var_smoothing=best_var_smoothing)
nb_best_.fit(X_train_res_nb, y_train_res_nb)
y_pred_nb = nb_best_.predict(X_testNB)

print("\n--- Final Model Performance on Test Set (Naive Bayes) ---")
print(f"Accuracy: {accuracy_score(y_testNB, y_pred_nb):.4f}")
print("\nClassification Report:")
print(classification_report(y_testNB, y_pred_nb))
print("\nConfusion Matrix:")
print(confusion_matrix(y_testNB, y_pred_nb))

--- Optimization Results (Naive Bayes) ---
{'var_smoothing': 2.794107883787569e-07}

--- Final Model Performance on Test Set (Naive Bayes) ---
Accuracy: 0.8360

Classification Report:
              precision    recall  f1-score   support

           0       0.98      0.84      0.90      9255
           1       0.30      0.84      0.45       787

    accuracy                           0.84     10042
   macro avg       0.64      0.84      0.68     10042
weighted avg       0.93      0.84      0.87     10042


Confusion Matrix:
[[7730 1525]
 [ 122  665]]