In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("./bank-additional/bank-additional/bank-additional-full.csv",delimiter=";")
df.head(300)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,47,self-employed,married,professional.course,no,no,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
296,49,blue-collar,divorced,high.school,no,no,yes,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
297,36,admin.,married,university.degree,no,yes,no,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
298,35,services,divorced,high.school,no,no,no,telephone,may,mon,...,3,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
299,38,unknown,married,unknown,unknown,no,no,telephone,may,mon,...,4,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [2]:
df = pd.DataFrame(df)

test = df['campaign'].unique()
test = np.sort(test)
print(test)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39 40 41 42 43 56]

In [3]:
allowed_y = {'yes', 'no'}
if not set(df['y'].unique()).issubset(allowed_y):
    raise ValueError(
        f"Target column contains values outside {allowed_y}"
    )

# ------------------------------------------------------------------
# 3. Count the occurrences using a cross‑tabulation
# ------------------------------------------------------------------
job_target_counts = pd.crosstab(df['campaign'], df['y'])

print("Counts of ‘yes’ / ‘no’ per job category:")
job_target_counts = pd.DataFrame(job_target_counts)
job_target_counts

Counts of ‘yes’ / ‘no’ per job category:

y            no   yes
campaign
1         15342  2300
2          9359  1211
3          4767   574
4          2402   249
5          1479   120
6           904    75
7           591    38
8           383    17
9           266    17
10          213    12
11          165    12
12          122     3
13           88     4
14           68     1
15           49     2
16           51     0
17           54     4
18           33     0
19           26     0
20           30     0
21           24     0
22           17     0
23           15     1
24           15     0
25            8     0
26            8     0
27           11     0
28            8     0
29           10     0
30            7     0
31            7     0
32            4     0
33            4     0
34            3     0
35            5     0
37            1     0
39            1     0
40            2     0
41            1     0
42            2     0
43            2     0
56            1     0

In [4]:
job_target_percentages = (
    job_target_counts.div(job_target_counts.sum(axis=1), axis=0) * 100
).round(2)

print("\nPercentages of ‘yes’ / ‘no’ per job category:")
print(job_target_percentages)

Percentages of ‘yes’ / ‘no’ per job category:
y             no    yes
campaign
1          86.96  13.04
2          88.54  11.46
3          89.25  10.75
4          90.61   9.39
5          92.50   7.50
6          92.34   7.66
7          93.96   6.04
8          95.75   4.25
9          93.99   6.01
10         94.67   5.33
11         93.22   6.78
12         97.60   2.40
13         95.65   4.35
14         98.55   1.45
15         96.08   3.92
16        100.00   0.00
17         93.10   6.90
18        100.00   0.00
19        100.00   0.00
20        100.00   0.00
21        100.00   0.00
22        100.00   0.00
23         93.75   6.25
24        100.00   0.00
25        100.00   0.00
26        100.00   0.00
27        100.00   0.00
28        100.00   0.00
29        100.00   0.00
30        100.00   0.00
31        100.00   0.00
32        100.00   0.00
33        100.00   0.00
34        100.00   0.00
35        100.00   0.00
37        100.00   0.00
39        100.00   0.00
40        100.00   0.00
41        100.00   0.00
42        100.00   0.00
43        100.00   0.00
56        100.00   0.00

### perulangan tidak berpengaruh, 1-4 panggilan saja efektif, jumlah orang nya saja yang di perbanyak, bukan kuantitas campaign kepada 1 orang