In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("./bank-additional/bank-additional/bank-additional-full.csv",delimiter=";")
df.head(100)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,45,services,married,professional.course,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
96,42,management,married,university.degree,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
97,53,admin.,divorced,university.degree,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
98,37,technician,single,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
99,44,blue-collar,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [3]:
df = pd.DataFrame(df)

test = df['pdays'].unique()
test = np.sort(test)
print(test)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  25  26  27 999]

In [4]:
allowed_y = {'yes', 'no'}

if not set(df['y'].unique()).issubset(allowed_y):
    raise ValueError(
        f"Target column contains values outside {allowed_y}"
    )

# ------------------------------------------------------------------
# 3. Count the occurrences using a cross‑tabulation
# ------------------------------------------------------------------
job_target_counts = pd.crosstab(df['pdays'], df['y'])

print("Counts of ‘yes’ / ‘no’ per job category:")
job_target_counts = pd.DataFrame(job_target_counts)
job_target_counts

Counts of ‘yes’ / ‘no’ per job category:

y         no   yes
pdays
0          5    10
1         18     8
2         24    37
3        141   298
4         55    63
5         17    29
6        123   289
7         20    40
8          6    12
9         29    35
10        22    30
11        13    15
12        32    26
13         8    28
14         9    11
15         8    16
16         5     6
17         6     2
18         3     4
19         2     1
20         1     0
21         0     2
22         1     2
25         0     1
26         0     1
27         0     1
999    36000  3673

In [5]:
job_target_percentages = (
    job_target_counts.div(job_target_counts.sum(axis=1), axis=0) * 100
).round(2)

print("\nPercentages of ‘yes’ / ‘no’ per job category:")
print(job_target_percentages)

Percentages of ‘yes’ / ‘no’ per job category:
y          no     yes
pdays
0       33.33   66.67
1       69.23   30.77
2       39.34   60.66
3       32.12   67.88
4       46.61   53.39
5       36.96   63.04
6       29.85   70.15
7       33.33   66.67
8       33.33   66.67
9       45.31   54.69
10      42.31   57.69
11      46.43   53.57
12      55.17   44.83
13      22.22   77.78
14      45.00   55.00
15      33.33   66.67
16      45.45   54.55
17      75.00   25.00
18      42.86   57.14
19      66.67   33.33
20     100.00    0.00
21       0.00  100.00
22      33.33   66.67
25       0.00  100.00
26       0.00  100.00
27       0.00  100.00
999     90.74    9.26

### mungkin drop saja

### dari campaign sebelumnya, bisa dilihat bahwa customer optimum di 1-14 hari menunggu sebelum akhirnya memutuskan untuk masuk ke program